feature: add landing page
Shivam010/bypass-cors pull request #8
Opened 2019-09-30 19:18 UTC by sudhabindu1

2019-10-04 19:09 UTC, Shivam010 requested changes
Hi @sudhabindu1 
I have reviewed your changes & requested some changes.

**NOTE:** Also, change the target branch to `dev`, merge and incorporate its changes and then, submit it, please

2019-10-04 19:09 UTC, Shivam010 commented on helper.go
> +	return
Set Content-type header to `text/html`
```suggestion
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	return
```

2019-10-04 19:09 UTC, Shivam010 commented on main.go
> +		serveLandingPage(w, r)
Do not call the landing page here...
As `URL` can be `nil` in some other case also, in such cases the `Return` method errors are overwritten.
```suggestion
```

2019-10-04 19:09 UTC, Shivam010 commented on helper.go
> -		})
Call landing page here...

2019-10-04 19:09 UTC, Shivam010 commented on public/index.html
> +</div>
Try to use all the data from Readme file in the Landing page

2019-10-07 18:34 UTC, sudhabindu1 commented
@Shivam010 I have made the changes as suggested. But not sure on the bit about using all the data from readme.md. I think it would make the homepage cluttered. And we're linking to the repo anyway.

2020-06-23 17:40 UTC, closed without merging